import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from './components/PrelineScriptWrapper';


const figTree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  weight: ["400", "500", "600", "700", "800", "900"],  
});

export const metadata: Metadata = {
  title: "Property Lising Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figTree.variable} antialiased`}
      >
        <PrelineScriptWrapper />
        {children}
      </body>
    </html>
  );
}
