import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from './components/PrelineScriptWrapper';


const figTree = Figtree({
  variable: "--font-figtree",
  weight: ["400", "500", "600", "700", "800", "900"], 
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Property Lising Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figTree.variable} antialiased`}
      >
        <PrelineScriptWrapper />
        {children}
      </body>
    </html>
  );
}
